# Generated by Django 4.1.7 on 2024-08-02 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True, unique=True)),
                ('contraseña', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administrador',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Buses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=200, null=True)),
                ('marca', models.CharField(max_length=200, null=True)),
                ('placa', models.CharField(max_length=200, null=True, unique=True)),
                ('año_fabricado', models.DateField(null=True)),
                ('motor', models.CharField(max_length=200, null=True)),
                ('año_modelo', models.DateField(null=True)),
                ('chasis', models.CharField(max_length=200, null=True)),
                ('kilometraje', models.CharField(max_length=10, null=True)),
                ('capacidad_pasajero', models.CharField(max_length=2, null=True)),
                ('ruedas', models.CharField(max_length=2, null=True)),
                ('ejes', models.CharField(max_length=1, null=True)),
                ('propietario', models.CharField(max_length=100, null=True)),
                ('cedula', models.CharField(max_length=10, null=True, unique=True)),
                ('telefono', models.CharField(max_length=10, null=True)),
                ('direccion', models.CharField(max_length=100, null=True)),
                ('numerobus', models.CharField(max_length=2, null=True)),
            ],
            options={
                'verbose_name': 'Bus',
                'verbose_name_plural': 'Buses',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CabeceraVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('buses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SisteWeb_Boleto.buses')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200, null=True, unique=True)),
                ('apellidos', models.CharField(max_length=200, null=True, unique=True)),
                ('cedula', models.CharField(max_length=10, null=True, unique=True)),
                ('telefonos', models.CharField(max_length=10, null=True)),
                ('tipo_licencia', models.CharField(choices=[('A', 'Tipo A'), ('B', 'Tipo B'), ('C', 'Tipo C'), ('D', 'Tipo D'), ('E', 'Tipo E'), ('F', 'Tipo F'), ('G', 'Tipo G'), ('A1', 'Tipo A1'), ('C1', 'Tipo C1')], default='A', max_length=2, null=True)),
                ('exp_licencia', models.DateField(null=True)),
                ('direccion', models.CharField(max_length=50, null=True)),
                ('edad', models.IntegerField(null=True)),
                ('provincia', models.CharField(max_length=50, null=True)),
                ('ciudad', models.CharField(max_length=50, null=True)),
                ('grupo_sanguineo', models.CharField(choices=[('A+', 'Tipo A+'), ('B+', 'Tipo B+'), ('O+', 'Tipo O+'), ('AB+', 'Tipo AB+'), ('A-', 'Tipo A-'), ('B-', 'Tipo B-'), ('O-', 'Tipo O-'), ('AB-', 'Tipo AB-')], default='A+', max_length=3, null=True)),
            ],
            options={
                'verbose_name': 'Chofer',
                'verbose_name_plural': 'Choferes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Copiloto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50, null=True)),
                ('apellidos', models.CharField(max_length=50, null=True)),
                ('cedula', models.CharField(max_length=10, null=True, unique=True)),
                ('telefono', models.CharField(max_length=10, null=True, unique=True)),
                ('direccion', models.CharField(max_length=50, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('provincia', models.CharField(max_length=20, null=True)),
                ('ciudad', models.CharField(max_length=20, null=True)),
                ('grupo_sanguineo', models.CharField(choices=[('A+', 'Tipo A+'), ('B+', 'Tipo B+'), ('O+', 'Tipo O+'), ('AB+', 'Tipo AB+'), ('A-', 'Tipo A-'), ('B-', 'Tipo B-'), ('O-', 'Tipo O-'), ('AB-', 'Tipo AB-')], default='A+', max_length=3, null=True)),
            ],
            options={
                'verbose_name': 'Copiloto',
                'verbose_name_plural': 'Copilotos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreRuta', models.CharField(max_length=50)),
                ('abreviatura', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100, null=True)),
                ('telefono', models.CharField(max_length=10, null=True, unique=True)),
                ('ciudad', models.CharField(max_length=100, null=True)),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1, null=True)),
                ('nom_user', models.CharField(max_length=15, null=True, unique=True)),
                ('contraseña', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasajero', models.CharField(max_length=50, null=True)),
                ('destino', models.CharField(max_length=50, null=True)),
                ('asiento', models.IntegerField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('costo', models.FloatField(blank=True, null=True)),
                ('modo_pago', models.CharField(max_length=50, null=True)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SisteWeb_Boleto.cabeceraventa')),
            ],
            options={
                'verbose_name': 'Detalle Venta',
                'verbose_name_plural': 'Detalles de Ventas',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='cabeceraventa',
            name='chofer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SisteWeb_Boleto.chofer'),
        ),
        migrations.AddField(
            model_name='cabeceraventa',
            name='copiloto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SisteWeb_Boleto.copiloto'),
        ),
        migrations.AddField(
            model_name='cabeceraventa',
            name='oficinista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SisteWeb_Boleto.usuario'),
        ),
        migrations.AddField(
            model_name='cabeceraventa',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SisteWeb_Boleto.ruta'),
        ),
    ]
